FROM php:8.4-apache

RUN apt-get update && apt-get install -y \
    zip \
    unzip
RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN a2enmod rewrite

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

COPY . /var/www/html

RUN composer install --no-dev --optimize-autoloader

WORKDIR /var/www/html/public

EXPOSE 80

CMD ["apache2-foreground"]
